name: Publish Libs

on:
  workflow_call:
    secrets:
      CHARMCRAFT_AUTH:
        required: true

jobs:
  publish-libs:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install charmcraft
        run: sudo snap install charmcraft --classic
      - name: Publish libs
        env:
          CHARMCRAFT_AUTH: "${{ secrets.CHARMCRAFT_AUTH }}"
        run: |
          charmcraft publish-lib charms.kubernetes_charm_libraries.v0.multus
          charmcraft publish-lib charms.kubernetes_charm_libraries.v0.kubernetes_hugepages_volumes_patch
