name: Publish Libs

on:
  workflow_call:
    secrets:
      CHARMCRAFT_AUTH:
        required: true

jobs:
  multus-lib-needs-publishing:
    runs-on: ubuntu-22.04
    outputs:
      needs-publishing: ${{ steps.changes.outputs.multus }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            multus:
              - 'lib/charms/kubernetes_charm_libraries/v0/multus.py'

  publish-multus-lib:
    name: Publish Multus library
    needs:
      - multus-lib-needs-publishing
    uses: canonical/sdcore-github-workflows/.github/workflows/publish-lib.yaml@main
    with:
      lib-name: "charms.kubernetes_charm_libraries.v0.multus"
    secrets: inherit

  hugepages-lib-needs-publishing:
    runs-on: ubuntu-22.04
    outputs:
      needs-publishing: ${{ steps.changes.outputs.hugepages }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            hugepages:
              - 'lib/charms/kubernetes_charm_libraries/v0/hugepages_volumes_patch.py'

  publish-hugepages-lib:
    name: Publish HugePages library
    needs:
      - hugepages-lib-needs-publishing
    uses: canonical/sdcore-github-workflows/.github/workflows/publish-lib.yaml@main
    with:
      lib-name: "charms.kubernetes_charm_libraries.v0.hugepages_volumes_patch"
    secrets: inherit
