name: Push

on:
  push:

jobs:
  lint-report:
    uses: ./.github/workflows/lint-report.yaml

  static-analysis:
    uses: ./.github/workflows/static-analysis.yaml

  unit-tests:
    uses: ./.github/workflows/unit-tests.yaml

  publish-charm:
    name: Publish Charm
    needs:
      [lint-report, static-analysis, unit-tests]
    if: ${{ github.ref_name == 'main' }}
    uses: ./.github/workflows/publish-charm.yaml

  publish-libs:
    name: Publish libraries
    needs:
      [lint-report, static-analysis, unit-tests, publish-charm]
    if: ${{ github.ref_name == 'main' }}
    uses: ./.github/workflows/publish-libs.yaml
